# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-shyam

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          working-directory: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-shyam'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6CEC3564BD1A48B2BD1CD3D169ABB178 }}
          package: ./dist/hello-world-app
